package:
  name: ngsparalog
  version: 1.3.3

build:
  script:
    - git clone --branch v1.3.3 https://github.com/tplinderoth/ngsParalog
    - cd ngsParalog
    - make
    - make clean

requirements:
  build:
    - make
    - git
    - htslib
    - samtools
    - numpy=1.23
  run:
    - python
    - htslib
    - samtools
    - r-truncnorm
    - r-docopt


about:
  home: https://github.com/tplinderoth/ngsParalog
  license: GPL-3.0
  summary: 'Copy number variation detection using NGS data'
  description: |
    ngsParalog is a program for detecting genomic regions that are problematic for short reading mapping using population-level, next generation sequencing (NGS) data.
  dev_url: https://github.com/tplinderoth/ngsParalog
  doc_url: https://github.com/tplinderoth/ngsParalog
  doc_source_url: https://github.com/tplinderoth/ngsParalog/blob/master/README.md